FROM python:3
ENV PYTHONUNBUFFERED 1

WORKDIR /code

RUN pip install gunicorn

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/

CMD python3 manage.py runserver 0.0.0.0:3002
