# Generated by Django 3.0.1 on 2020-01-15 10:58

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191229_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('DECLINED', 'DECLINED')], default=api.models.InvitationStatus['PENDING'], max_length=255),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('userId', 'workspace')},
        ),
    ]
