# Generated by Django 3.0.1 on 2020-01-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200115_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sender',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
