# Generated by Django 3.0.1 on 2020-04-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200426_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('user_id', 'workspace')},
        ),
    ]
