# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Worko Workspace

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: workspace
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-line-length=127 --exit-zero --show-source --statistics

    - name: Test with pytest
      run: |
        python3 manage.py test
  
  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build docker image
      run: |
         docker build -t worko/workspace:${{ github.sha }} .
         
    - name: Google Cloud Countainer Registry
      uses: mattes/gce-docker-push-action@v1.0.0
      with:
        # Contents of a Service Account JSON Key
        creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        # Source image name
        src: worko/workspace:${{ github.sha }}
        # Destination image name
        dst: gcr.io/euphoric-stone-294521/workspace:${{ github.sha }}
